# Use when connecting to Docker Streams Quick Start Edition 4.2.4+
# on the same host
# Docker Networking is constantly evolving but at the time of writing
# version 17.0.x-ce required using the bridge network with 
# Docker Streams Quick Start Edition.
#
# streamsexporter .env file should point to the Streams containername:
#   streamsdocker4240 (or current name)

version: '2'
volumes:
  prometheus_data:
  grafana_data:
services:
  streamsexporter:
    env_file:
      - .env
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
     - 25500:25500
    environment:
      - STREAMS_DOMAIN_ID
    network_mode: "bridge"
    external_links:
     - streamsdocker4240:streamsqse
  prometheus:
    image: "prom/prometheus:v2.1.0"
    ports:
     - 9090:9090
    volumes:
     - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     - prometheus_data:/prometheus
    network_mode: "bridge"
    links:
     - streamsexporter
  grafana:
    image: "grafana/grafana:5.0.4"
    ports:
     - 3000:3000
    volumes:
     - ../grafana:/etc/grafana
     - ../dashboards:/streams/sample/dashboards:ro
     - grafana_data:/var/lib/grafana
    network_mode: "bridge"
    links:
     - prometheus
