# Use when Streams Domain is not on the same Docker Host
# For example:
#   Streams on bare-metal
#   Streams on a VM
#   Streams in Docker on another host
#   Streams on Kubernetes (Kubernetes networking is different than Docker)

version: '2'
volumes:
  prometheus_data:
  grafana_data:
services:
  streamsexporter:
    env_file:
      - .env
    # Use build or image, image pulls from Dockerhub, build is for local build
    image: bmwilli1/streams-metric-exporter:4.0.0
    #build: 
      #context: ..
      #dockerfile: docker/Dockerfile
    ports:
     - 25500:25500
  prometheus:
    image: "prom/prometheus:v2.17.1"
    ports:
     - 9090:9090
    volumes:
     - prometheus_data:/prometheus
     - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: "grafana/grafana:6.7.2"
    ports:
     - 3000:3000
    volumes:
     - grafana_data:/var/lib/grafana
     - ../grafana/grafana.ini:/etc/grafana/grafana.ini
     - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
     # Uncomment if you want dashboards auto-loaded, but no changes can be made
     #- ../grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards 
     #- ../dashboards:/streams/sample/dashboards:ro
