version: '2'
volumes:
  prometheus_data:
  grafana_data:
services:
  streamsexporter:
    env_file:
      - .env
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
     - 25500:25500
    environment:
      - STREAMS_DOMAIN_ID
      - STREAMS_INSTANCE_ID
      - STREAMS_EXPORTER_HOST=0.0.0.0
      - STREAMS_EXPORTER_JMXCONNECT
  prometheus:
    image: "prom/prometheus:v1.8.2"
    ports:
     - 9090:9090
    volumes:
     - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     - prometheus_data:/prometheus
  grafana:
    image: "grafana/grafana:4.6.1"
    ports:
     - 3000:3000
    volumes:
     - grafana_data:/var/lib/grafana
