version: '2'
services:
  streamsexporter:
    env_file:
      - .env
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
     - 25500:25500
#    volumes:
#     - /home/brian/git2/streamsx.jmxclients/streams-metric-exporter:/opt/app
    environment:
      - STREAMS_DOMAIN_ID
      - STREAMS_INSTANCE_ID
      - STREAMS_EXPORTER_HOST=0.0.0.0
      - STREAMS_EXPORTER_JMXCONNECT
  prometheus:
    image: "prom/prometheus"
    ports:
     - 9090:9090
    volumes:
     - ./prometheus-data/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: "grafana/grafana"
    ports:
     - 3000:3000
