# Use when connecting to Docker Streams Quick Start Edition 4.2.4+
# on the same host
# Docker Networking is constantly evolving but at the time of writing
# version 17.0.x-ce required using the bridge network with 
# Docker Streams Quick Start Edition.
#
# streamsexporter .env file should point to the Streams containername:
#   streamsdocker4240 (or current name)

version: '2'
volumes:
  prometheus_data:
  grafana_data:
services:
  streamsexporter:
    env_file:
      - .env
    # Use build or image, image pulls from Dockerhub, build is for local build
    image: bmwilli1/streams-metric-exporter:4.0.0
    #build: 
      #context: ..
      #dockerfile: docker/Dockerfile
    ports:
     - 25500:25500
    network_mode: "bridge"
    external_links:
     - streamsdocker4300:streamsqse
  prometheus:
    image: "prom/prometheus:v2.17.1"
    ports:
     - 9090:9090
    volumes:
     - prometheus_data:/prometheus
     - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "bridge"
    links:
     - streamsexporter
  grafana:
    image: "grafana/grafana:6.7.2"
    ports:
     - 3000:3000
    volumes:
     - grafana_data:/var/lib/grafana
     - ../grafana/grafana.ini:/etc/grafana/grafana.ini
     - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
     # Uncomment if you want dashboards auto-loaded, but no changes can be made
     #- ../grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards 
     #- ../dashboards:/streams/sample/dashboards:ro
    network_mode: "bridge"
    links:
     - prometheus
