{
 "title": "IBM Streams Instance Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instancename", "label": "Streams Instance", "query": "label_values(instancename)" },
   { "name": "jobname", "label": "Job Name", "query": "label_values(jobname)" }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "streams_instance_status{instancename=\"$instancename\"}"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "streams_instance_jobCount{instancename=\"$instancename\"}"
    }
   ]
  },
  {
   "title": "Instance \"$instancename\"  Job Health",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "streams_job_healthy{instancename=\"$instancename\",jobname=~\"$jobname\"}",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Streams PE CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (jobname,peid) (rate(streams_pe_nCpuMilliseconds{instancename=~\"$instancename\",jobname=~\"$jobname\"}[5m]))",
     "legendFormat": "{{jobname}} peid: {{peid}}"
    }
   ]
  },
  {
   "title": "Job PE Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "streams_job_pecount{instancename=~\"$instancename\",jobname=~\"$jobname\"}",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Streams PE Resident Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (jobname, peid) (streams_pe_nResidentMemoryConsumption{instancename=~\"$instancename\",jobname=~\"$jobname\"})",
     "legendFormat": "{{jobname}} peid: {{peid}}"
    }
   ]
  },
  {
   "title": "PE Congestion",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "streams_pe_op_connection_congestionFactor{instancename=~\"$instancename\",jobname=~\"$jobname\"}",
     "legendFormat": "{{jobname}} peid:{{peid}}"
    }
   ]
  },
  {
   "title": "PE OutputPort Tuples Submitted Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_op_nTuplesSubmitted{instancename=~\"$instancename\",jobname=~\"$jobname\"}[5m])",
     "legendFormat": "{{jobname}} peid: {{peid}} Index: {{index}}"
    }
   ]
  },
  {
   "title": "PE InputPort Tuples Processed Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_ip_nTuplesProcessed{instancename=~\"$instancename\",jobname=~\"$jobname\"}[5m])",
     "legendFormat": "{{jobname}} peid: {{peid}} Index: {{index}}"
    }
   ]
  },
  {
   "title": "PE OutputPort Bytes Submitted Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_op_nTupleBytesSubmitted{instancename=~\"$instancename\",jobname=~\"$jobname\"}[5m])",
     "legendFormat": "{{jobname}} peid: {{peid}} Index: {{index}}"
    }
   ]
  },
  {
   "title": "PE InputPort Bytes Processed Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_ip_nTupleBytesProcessed{instancename=~\"$instancename\",jobname=~\"$jobname\"}[5m])",
     "legendFormat": "{{jobname}} peid: {{peid}} Index: {{index}}"
    }
   ]
  },
  {
   "title": "PE Launch Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "streams_pe_launchCount{instancename=~\"$instancename\",jobname=~\"$jobname\"}",
     "legendFormat": "{{jobname}}:{{peid}}"
    }
   ]
  },
  {
   "title": "Tuples Processed Rate by Operator",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(streams_operator_ip_nTuplesProcessed{instancename=~\"$instancename\",jobname=~\"$jobname\"}[2m])",
     "legendFormat": "{{operatorname}} (pe: {{peid}})"
    }
   ]
  }
 ]
}