{
 "title": "IBM Streams Resource Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "role",
    "label": "Resource Role",
    "query": "label_values(streams_resource_role, role)"
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": "label_values(streams_resource_role{role=~\"$role\"} ,resource)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "streams_resource_status{resource=~\"$resource\"} * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "streams_resource_cpuSpeed{resource=~\"$resource\"}  * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "streams_resource_cpuUtilization{resource=~\"$resource\"}  * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "(streams_resource_loadAverage{resource=~\"$resource\"}/100) * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "streams_resource_nProcessors{resource=~\"$resource\"} * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "streams_resource_memoryTotal{resource=~\"$resource\"} * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "streams_resource_memoryFree{resource=~\"$resource\"} * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "streams_resource_memoryUtilization{resource=~\"$resource\"} * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "streams_resource_networkSpeed{resource=~\"$resource\"} * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "streams_resource_networkUtilization{resource=~\"$resource\"} * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"}"
    },
    {
     "expr": "count(count by (resource,peid) (streams_pe_health{resource=~\"$resource\"} * on (resource) group_left(role) streams_resource_role{resource=~\"$resource\",role=~\"$role\"} )) by (resource)"
    }
   ]
  },
  { "title": "$resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "resource" },
  {
   "title": "PE Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "streams_pe_launchCount{resource=~\"$resource\"} + 0",
     "legendFormat": "launchcount"
    },
    {
     "expr": "streams_pe_status{resource=~\"$resource\"} + 0"
    },
    {
     "expr": "streams_pe_health{resource=~\"$resource\"} + 0"
    }
   ]
  },
  {
   "title": "PE CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_nCpuMilliseconds{resource=~\"$resource\"}[2m])",
     "legendFormat": "{{jobname}} peid: {{peid}}"
    }
   ]
  },
  {
   "title": "1m Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "streams_resource_cpuUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "targets": [
    {
     "expr": "streams_resource_memoryUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  { "title": "$resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "PE Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "streams_pe_launchCount{resource=~\"$resource\"} + 0",
     "legendFormat": "launchcount"
    },
    {
     "expr": "streams_pe_status{resource=~\"$resource\"} + 0"
    },
    {
     "expr": "streams_pe_health{resource=~\"$resource\"} + 0"
    }
   ]
  },
  {
   "title": "PE CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_nCpuMilliseconds{resource=~\"$resource\"}[2m])",
     "legendFormat": "{{jobname}} peid: {{peid}}"
    }
   ]
  },
  {
   "title": "1m Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "streams_resource_cpuUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "targets": [
    {
     "expr": "streams_resource_memoryUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  { "title": "$resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "PE Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "streams_pe_launchCount{resource=~\"$resource\"} + 0",
     "legendFormat": "launchcount"
    },
    {
     "expr": "streams_pe_status{resource=~\"$resource\"} + 0"
    },
    {
     "expr": "streams_pe_health{resource=~\"$resource\"} + 0"
    }
   ]
  },
  {
   "title": "PE CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_nCpuMilliseconds{resource=~\"$resource\"}[2m])",
     "legendFormat": "{{jobname}} peid: {{peid}}"
    }
   ]
  },
  {
   "title": "1m Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "streams_resource_cpuUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 18 },
   "targets": [
    {
     "expr": "streams_resource_memoryUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  { "title": "$resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "PE Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "streams_pe_launchCount{resource=~\"$resource\"} + 0",
     "legendFormat": "launchcount"
    },
    {
     "expr": "streams_pe_status{resource=~\"$resource\"} + 0"
    },
    {
     "expr": "streams_pe_health{resource=~\"$resource\"} + 0"
    }
   ]
  },
  {
   "title": "PE CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_nCpuMilliseconds{resource=~\"$resource\"}[2m])",
     "legendFormat": "{{jobname}} peid: {{peid}}"
    }
   ]
  },
  {
   "title": "1m Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "streams_resource_cpuUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 24 },
   "targets": [
    {
     "expr": "streams_resource_memoryUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  { "title": "$resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "PE Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "streams_pe_launchCount{resource=~\"$resource\"} + 0",
     "legendFormat": "launchcount"
    },
    {
     "expr": "streams_pe_status{resource=~\"$resource\"} + 0"
    },
    {
     "expr": "streams_pe_health{resource=~\"$resource\"} + 0"
    }
   ]
  },
  {
   "title": "PE CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_nCpuMilliseconds{resource=~\"$resource\"}[2m])",
     "legendFormat": "{{jobname}} peid: {{peid}}"
    }
   ]
  },
  {
   "title": "1m Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "streams_resource_cpuUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 30 },
   "targets": [
    {
     "expr": "streams_resource_memoryUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  { "title": "$resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "PE Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "streams_pe_launchCount{resource=~\"$resource\"} + 0",
     "legendFormat": "launchcount"
    },
    {
     "expr": "streams_pe_status{resource=~\"$resource\"} + 0"
    },
    {
     "expr": "streams_pe_health{resource=~\"$resource\"} + 0"
    }
   ]
  },
  {
   "title": "PE CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_nCpuMilliseconds{resource=~\"$resource\"}[2m])",
     "legendFormat": "{{jobname}} peid: {{peid}}"
    }
   ]
  },
  {
   "title": "1m Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "streams_resource_cpuUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 36 },
   "targets": [
    {
     "expr": "streams_resource_memoryUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  { "title": "$resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "PE Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "streams_pe_launchCount{resource=~\"$resource\"} + 0",
     "legendFormat": "launchcount"
    },
    {
     "expr": "streams_pe_status{resource=~\"$resource\"} + 0"
    },
    {
     "expr": "streams_pe_health{resource=~\"$resource\"} + 0"
    }
   ]
  },
  {
   "title": "PE CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(streams_pe_nCpuMilliseconds{resource=~\"$resource\"}[2m])",
     "legendFormat": "{{jobname}} peid: {{peid}}"
    }
   ]
  },
  {
   "title": "1m Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 42 },
   "targets": [
    {
     "expr": "streams_resource_cpuUtilization{resource=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 42 },
   "targets": [
    {
     "expr": "streams_resource_memoryUtilization{resource=~\"$resource\"}"
    }
   ]
  }
 ]
}