{
 "title": "IBM Streams Domain Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instancename", "label": "Streams Instance", "query": "label_values(instancename)" }
  ]
 },
 "panels": [
  {
   "title": "Domain Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    { "expr": "streams_domain_status + 0" }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "streams_domain_status" }
   ]
  },
  {
   "title": "Started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    { "expr": "streams_domain_startTime + 0" }
   ]
  },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - (streams_domain_startTime/1000)"
    }
   ]
  },
  {
   "title": "Created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    { "expr": "streams_domain_creationTime" }
   ]
  },
  {
   "title": "Instance Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(streams_domain_instanceCount)"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(streams_instance_jobCount{instancename=~\"$instancename\"})"
    }
   ]
  },
  {
   "title": "Instance Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "streams_instance_status{instancename=~\"$instancename\"}",
     "legendFormat": "{{instancename}}"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 3 },
   "targets": [
    { "expr": "streams_job_submitTime + 0" },
    { "expr": "streams_job_health + 0" },
    { "expr": "streams_job_status + 0" }
   ]
  },
  {
   "title": "Resource Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 3 },
   "targets": [
    {
     "expr": "count(count by (resource,peid) (streams_pe_health{instancename=~\"$instancename\"})) by (resource)"
    },
    {
     "expr": "streams_resource_status{instancename=~\"$instancename\"} + 0",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Streams Jobs CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(streams_job_nCpuMilliseconds{instancename=~\"$instancename\"}[5m])",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Streams Job Resident Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "streams_job_nResidentMemoryConsumption{instancename=~\"$instancename\"}",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Job Max Congestion",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "streams_job_max_congestionFactor{instancename=~\"$instancename\"}",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Streams Resource Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "streams_resource_memoryTotal{instancename=~\"$instancename\"}",
     "legendFormat": "{{resource}} (total memory)"
    },
    {
     "expr": "streams_resource_memoryTotal{instancename=~\"$instancename\"} - streams_resource_memoryFree{instancename=~\"$instancename\"}",
     "legendFormat": "{{resource}} (used memory)"
    }
   ]
  }
 ]
}