{
 "title": "IBM Streams Job Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instancename", "label": "Streams Instance", "query": "label_values(instancename)" },
   { "name": "jobname", "label": "Job Name", "query": "label_values(jobname)" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "streams_instance_status{instancename=\"$instancename\"}"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "streams_instance_jobCount{instancename=\"$instancename\"}"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "streams_job_submitTime{instancename=\"$instancename\",jobname=~\"$jobname\"} + 0"
    },
    {
     "expr": "count by (jobname) (streams_operator_relativeOperatorCost{instancename=\"$instancename\",jobname=~\"$jobname\"} + 0)"
    },
    {
     "expr": " count by (jobname) (streams_pe_status{instancename=\"$instancename\",jobname=~\"$jobname\"} + 0)"
    },
    {
     "expr": "streams_job_health{instancename=\"$instancename\",jobname=~\"$jobname\"} + 0"
    },
    {
     "expr": "streams_job_status{instancename=\"$instancename\",jobname=~\"$jobname\"} + 0"
    }
   ]
  },
  {
   "title": "PE Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count by (jobname,peid) (streams_operator_relativeOperatorCost{instancename=~\"$instancename\",jobname=~\"$jobname\"}) + 0"
    },
    {
     "expr": "streams_pe_launchCount{instancename=~\"$instancename\",jobname=~\"$jobname\"} + 0",
     "legendFormat": "launchcount"
    },
    {
     "expr": "streams_pe_status{instancename=~\"$instancename\",jobname=~\"$jobname\"} + 0"
    },
    {
     "expr": "streams_pe_health{instancename=~\"$instancename\",jobname=~\"$jobname\"} + 0"
    }
   ]
  },
  {
   "title": "Tuples Submitted Rate by Operator (Source Operators)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (jobname, operatorname) (rate(streams_operator_op_nTuplesSubmitted{instancename=~\"$instancename\",jobname=~\"$jobname\",operatorname=~\".*(?:[Bb]eacon|[Ss]ource|[Ss]can|[R]ead).*\"}[2m]))",
     "legendFormat": "{{jobname}}: {{operatorname}}"
    }
   ]
  },
  {
   "title": "Tuples Processed Rate by Operator (Sink Operators)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (jobname, operatorname) (rate(streams_operator_ip_nTuplesProcessed{instancename=~\"$instancename\",jobname=~\"$jobname\",operatorname=~\".*(?:[Ss]ink|[Ww]rite|[Oo]ut).*\"}[2m]))",
     "legendFormat": "{{jobname}}: {{operatorname}}"
    }
   ]
  },
  {
   "title": "Relative Operator Cost  (top 10)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sort_desc((sum(streams_operator_relativeOperatorCost{instancename=~\"$instancename\",jobname=~\"$jobname\"}) by (jobname, operatorname))) ",
     "legendFormat": "{{jobname}}: {{operatorname}}"
    }
   ]
  },
  {
   "title": "PE Congestion",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "streams_pe_op_connection_congestionFactor{instancename=~\"$instancename\",jobname=~\"$jobname\"} > 0",
     "legendFormat": "{{jobname}}, peid:{{peid}}"
    }
   ]
  },
  {
   "title": "Streams PE CPU Milliseconds Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (jobname,peid) (rate(streams_pe_nCpuMilliseconds{instancename=~\"$instancename\",jobname=~\"$jobname\"}[2m]))",
     "legendFormat": "{{jobname}}, peid: {{peid}}"
    }
   ]
  },
  {
   "title": "PE Resident Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (jobname, peid) (streams_pe_nResidentMemoryConsumption{instancename=~\"$instancename\",jobname=~\"$jobname\"})",
     "legendFormat": "{{jobname}}, peid: {{peid}}"
    }
   ]
  }
 ]
}